name: biobombe
channels:
- conda-forge
- defaults
dependencies:
- python>=3.7<3.12
- pandas>=0.23.4
- xlrd>=1.1.0
- numpy>=1.15.2
- dask-searchcv>=0.2.0
- seaborn>=0.9.0
- scikit-learn>=0.20.1
- dask-searchcv>=0.2.0
- jupyter>=1.0.0
- ipykernel>=4.8.1
- nb_conda_kernels>=2.1.0
- openpyxl>=2.5.1
- requests>=2.21.0
- lxml>=4.3.1
- cuda-runtime=12.5.1.*
- pytorch=2.3.1
- r-base>=3.6
- r-dplyr>=0.7.6
- r-tidyr>=0.8.0
- r-readr>=1.1.1
- r-readxl>=1.1.0
- r-ggplot2>=2.2.1
- r-cowplot>=0.9.3
- r-heatmap3>=1.1.1
- r-ggrepel>=0.8.0
- r-irkernel>=0.8.11
- r-optparse>=1.6.0
- pip>=12
- pip:
  - git+https://github.com/dhimmel/hetio@9d9ef1320ee47609e3c61c9f4918531d3c1c8c96
  - git+https://github.com/greenelab/tybalt@739cfb894426b2dcedcf3ed48e3a43733a5cac2e
  - git+https://github.com/greenelab/hetmech@dc1c14b60b1cb19f87d7ff6d1679e0dae72adc8d
  - git+https://github.com/grisslab/grein_loader@573a70e7160c77ab8e5be9f3e24d372e34befefc
